### ISSUE TITLE
Training issue - name 'is_training' is not defined

### ISSUE THREAD

**Issue by AmitRozner** [Wuyxin/DISC#3]
When trying to run the training I face the following issue:
  disc/disc/utils/loss.py", line 198, in get_stats
      group_str = self.group_str(idx, is_training) if 'Meta' in self.args.dataset else self.group_str(idx)
  NameError: name 'is_training' is not defined

Can you assist? This is indeed not defined so I am unsure how it worked for you. 
Thank you!

**Comment by Wuyxin** [comment]
Hi,

You are right, this is a bug which we didn't notice when cleaning our codebase. The reason is that we were testing on CUB dataset and the bug only triggers on MetaShift dataset. Apologies for the confusion. I believe it's fixed rn. 

Thanks a lot for letting me know!

**Comment by Wuyxin** [comment]
Close this issue after the fix, pls let me know if there are more Qs!
